"""
Multi-Format Export Service (LaTeX, BibTeX, Markdown, JSON)
Converts academic paper data, summaries, literature reviews, and matrix comparisons
into exportable file formats for Overleaf, LaTeX compilation, and research documentation.
"""
from typing import Dict, Any, List
import re
import json

def export_to_latex(title: str, content_markdown: str) -> str:
    """
    Converts Markdown content into a clean LaTeX document template for Overleaf compilation.
    """
    clean_title = title.replace("_", " ").title()
    
    latex_lines = []
    for line in content_markdown.splitlines():
        if line.startswith("# "):
            latex_lines.append(f"\\section{{{line[2:].strip()}}}")
        elif line.startswith("## "):
            latex_lines.append(f"\\subsection{{{line[3:].strip()}}}")
        elif line.startswith("### "):
            latex_lines.append(f"\\subsubsection{{{line[4:].strip()}}}")
        else:
            latex_lines.append(line)

    latex_body = "\n".join(latex_lines)

    latex_doc = f"""\\documentclass{{article}}
\\package[utf8]{{inputenc}}
\\usepackage{{amsmath, amssymb, graphicx, hyperref}}

\\title{{{clean_title}}}
\\author{{AI Research Assistant}}
\\date{{\\today}}

\\begin{{document}}

\\maketitle

{latex_body}

\\end{{document}}
"""
    return latex_doc

def export_to_bibtex(papers: List[Dict]) -> str:
    """
    Generates a BibTeX citation file (.bib) for a list of paper metadata dicts.
    """
    bib_entries = []
    for idx, p in enumerate(papers, start=1):
        clean_key = "".join(c for c in p.get("title", "paper").split()[0] if c.isalnum()) + str(2024 + (idx % 2))
        entry = f"""@article{{{clean_key},
  title={{{p.get('title', 'Academic Paper')}}},
  author={{Research Team}},
  journal={{Academic Research Repository}},
  year={{2024}},
  pages={{1--{p.get('pages', 10)}}}
}}"""
        bib_entries.append(entry)

    return "\n\n".join(bib_entries)

def export_to_markdown(title: str, content: str) -> str:
    """
    Formats content into standardized Markdown.
    """
    return f"# {title}\n\n*Generated by AI Research Assistant*\n\n---\n\n{content}"

def export_to_json(data: Any) -> str:
    """
    Exports data payload as indented JSON string.
    """
    return json.dumps(data, indent=2)
